### PR TITLE
chore: lock @types jasmine

### PR DESCRIPTION
**Pull request by Foxandxss**

### CODE REVIEW

**Comment by Dev4mir** [comment]
I changed `@types/jasmine": "2.5.36"` but still not working

**Comment by Foxandxss** [comment]
define what is not working.

**Comment by Dev4mir** [comment]
I tried to `npm start` but still receive same error 
`node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.`

**Comment by Foxandxss** [comment]
are you sure you deleted the old @types from node_modules? Delete the folder and `npm install` again.

**Comment by Dev4mir** [comment]
thanks it's working now.
sorry i'm new to angular thanks again :-)

**Comment by Foxandxss** [comment]
Whether this is not really an angular issue, if you update your package.json and even if you `npm install`, iy won't replace packages. That mean that if you change the line of jasmine by hand, even if you `npm install` it will ignore it. You would need to remove the package from `node_modules` and install it again.

**Pull request merged**
