### PR TITLE
Recommend Angular CLI for new projects

### PR DESCRIPTION
**Pull request by Meligy**
Let the users know they are better off starting their new Angular projects based on Angular CLI.

### CODE REVIEW

**Comment by MarkPieszak** [comment]
Looks like a good idea to me 👍

**Comment by Foxandxss** [comment]
This project is still the root project for the docs.

We are planning a few things that could get rid of it.

So stay tuned.

**Comment by jlSites** [comment]
if new projs starting from angular cli, what about the 'quickstart' seed? is it dead or not recommended any more?

**Comment by Meligy** [comment]
My understanding is that this project serves as a local equivalent of the online demo that's available in the Angular docs. It's meant to be as close as possible to the online thing, without the overhead of actually loading all packages from remote sources etc. 

The disclaimer about it being non optimal for production has been for a while. It just needed an answer to the next logical question "If this isn't good for production, what is?", which this PR addresses.

**Comment by arrmixer** [comment]
not sure if this helps but I did the tutorial using the Angular cli build instead of the quickstart. Except for a few minor changes works fine.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Pull request closed without merging**
