### PR TITLE
chore: reword readme

### PR DESCRIPTION
**Pull request by Foxandxss**
Talking with John and Tero the other day about this readme.

I think that it is best if we focus the repo just as a mirror of the source code at angular.io and we reword it a bit to talk about tutorials instead of projects. People is taking this as a repository of truth about working with new ng2 apps and that is the wrong idea.

### CODE REVIEW

**Comment by wardbell** [comment]
I agree that we shouldn't sell it as the ultimate anything. I like the mirroring statement.

But it is a viable starting place for experimental projects and I dont agree with pinning I to the samples or the ToH.

We should talk about why you think it should be so restrictive.

**Comment by Foxandxss** [comment]
> We should talk about why you think it should be so restrictive.

Sounds good to me :+1:

**Comment by Foxandxss** [comment]
This needs a review.

**Comment by wardbell** [comment]
Sorry, dude.  I went a different direction with this. I am updating the README to make the limitations more clear.

**Pull request closed without merging**
