### PR TITLE
Fix many 'Can not find name xxxx' issue.

### PR DESCRIPTION
**Pull request by zslucky**
Hello, I'm using node 4.2.6, npm 2.14.12. 
After `npm install` and `npm start`, it will throw many *Cannot find name xxxx* errors.
Then exits with follow errors.
```bash
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
```
After run `typings install` will solve the issue.

### CODE REVIEW

**Comment by Foxandxss** [comment]
The problem is that our tools install typings after install, question is: why they don't for some people.

**Comment by zslucky** [comment]
Sounds strange, thank you for reply, maybe I need a deep investigation~

**Comment by Foxandxss** [comment]
You tell me. I get the typings by default, other people too but suddenly, that is not the case for some Ubuntu users. Weird is that you are using OSX. Perhaps is beacuse you are using an old node & npm, but it shouldn't.

**Comment by zslucky** [comment]
Hello,  after a quick search, this issue may due to I used the `sudo`, here are 2 kind of solutions
1.Run npm install with the --unsafe-perm flag:
```bash
[sudo] npm install --unsafe-perm
```
2.Add the unsafe-perm flag to your `package.json`:
```javascript
"config": {
    "unsafe-perm":true
}
```
But use `unsafe-perm` may have risk one guy mentioned.

**Comment by wardbell** [comment]
Closing because we're getting very far from the purpose of this repo, there is no actual diagnosis and no solution. Happy to look again when someone has a repro and an answer. No point in pretending we're going to do anything with this as it stands now.

**Pull request closed without merging**
