### PR TITLE
Generate code coverage of typescript code for unit tests

### PR DESCRIPTION
**Pull request by rohans84**
Changes made:
1. Added npm packages: karma-coverage, karma-sourcemap-loader and remap-istanbul
2. updated karma.conf.js to use the newly added packages to generate coverage of transpiled code
3. added npm test : test-once-cover to generate coverage report in html format

Steps followed to generate code coverage:
1. Using karma-coverage and karma-sourcemap-loader, karma generates code coverage of transpiled files
2. using remap-istanbul package, the coverage of typescript code is generated
3  The code coverage report is finally generated in html format under coverage-report/remapped/html-report/ folder.

### CODE REVIEW

**Comment by rohans84** [comment]
I signed the CLA using my id rohans84

**Comment by wardbell** [comment]
Code coverage is a great idea but is not consistent with the relative simplicity and maintainability we seek for this QuickStart seed. Thanks but we'll have to decline your suggestion.

**Comment by rohans84** [comment]
THanks for looking into it. I can understand the need to make quickstart app as lightweight as possible. However, for Enterprise use cases, code coverage is how the unit testing is measured.

**Comment by wardbell** [comment]
Of course. Just out of scope for here. Good luck!

**Pull request closed without merging**
