### PR TITLE
Separate compiled to bring in line with tour-of-heroes guide

### PR DESCRIPTION
**Pull request by jmetev1**
Tour of heroes guide in parts 1 and 2 shows only having your .ts files in src. So I thought I'd make the repo that way instead of having mixed up jumble of .ts and .js files.

### CODE REVIEW

**Comment by Foxandxss** [comment]
I don't understand.

**Comment by jmetev1** [comment]
Tour of heroes seems aimed at very new people. The repo is originally setup to compile from src and output compiled .js files back to src. People new to angular or new to the concept of having separate source .ts files and compiled .js files are likely to get confused. I thought it would be better to separate them.

**Comment by Foxandxss** [comment]
You can always ignore the compiled .js in your editor so they are never seen.

**Comment by jmetev1** [comment]
There are ways to deal with it if you're an advanced user. But if the quickstart is aimed at people very new to angular and new to having separate compiled files, it would be nice if the compiled files weren't mixed in with the .ts files that have almost the same name and are superficially similar in content.

**Comment by Foxandxss** [comment]
In any case, this repo will be deprecated really soon in favor of starting with the CLI.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Pull request closed without merging**
