### PR TITLE
add unit test example

### PR DESCRIPTION
**Pull request by alisherabd**
Since there is already e2e example, I thought maybe we should add unit test example as well.

### CODE REVIEW

**Comment by alisherabd** [comment]
I signed it!

**Comment by alisherabd** [comment]
I signed it!

**Comment by Foxandxss** [comment]
What about the one we already have here? https://github.com/angular/quickstart/blob/master/app/app.component.spec.ts

**Comment by alisherabd** [comment]
You are right. It's not really needed here, therefore I am closing it.

Thanks

**Pull request closed without merging**
