### PR TITLE
chore: add base href

### PR DESCRIPTION
**Pull request by Foxandxss**

### CODE REVIEW

**Comment by filipesilva** [comment]
LGTM

**Comment by atiris** [comment]
Hi, 
why you modified index.html to contain 'base href="/"' element twice?
Does it have any special meaning for angular?

**Comment by Foxandxss** [comment]
Uhh, honest mistake. Feel free to open a PR. I had this PR hanging and I thought we never did it.

**Comment by atiris** [comment]
Done, here: https://github.com/angular/quickstart/pull/395

**Pull request merged**
